[project]
name = "dlai-shortcourse-notebooks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=0.31.0",
    "altair",
    "cohere",
    "comet-ml>=3.49.11",
    "datasets>=3.6.0",
    "datetime>=6.0",
    "ddgs>=9.13.0",
    "diffusers>=0.34.0",
    "docarray>=0.41.0",
    "dspy>=2.6.27",
    "einops>=0.8.1",
    "faiss-cpu",
    "fastapi>=0.115.14",
    "gradio>=6.11.0",
    "graphviz>=0.21",
    "hf-xet",
    "inflect",
    "instructor>=1.9.0",
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "jupyter-bokeh>=4.0.5",
    "langchain>=1.2.15",
    "langchain-classic>=1.0.3",
    "langchain-community>=0.4.1",
    "langchain-experimental>=0.4.1",
    "langchain-openai>=1.1.12",
    "langchain-tavily>=0.2.17",
    "langgraph>=1.1.6",
    "langgraph-checkpoint-sqlite>=3.0.3",
    "librosa",
    "litellm>=1.73.6",
    "matplotlib>=3.10.3",
    "mistralai",
    "mlflow>=3.1.1",
    "numpy>=2.3.1",
    "openai>=1.93.0",
    "opencv-python>=4.11.0.86",
    "outlines>=1.0.4",
    "pandas>=2.3.0",
    "panel>=1.8.10",
    "phonemizer",
    "pillow>=11.2.1",
    "plotly>=5.9.0",
    "python-dotenv>=1.1.1",
    "quanto",
    "requests>=2.32.4",
    "safetensors",
    "scikit-image>=0.25.2",
    "scikit-learn>=1.7.0",
    "scipy>=1.16.0",
    "seaborn>=0.12.2",
    "sentence-transformers",
    "sentencepiece",
    "soundfile",
    "streamlit>=1.30.0",
    "tavily>=1.1.0",
    "tiktoken>=0.12.0",
    "timm",
    "torch>=2.11.0",
    "torchaudio>=2.11.0",
    "torchvision>=0.26.0",
    "transformers>=4.41.2",
    "ultralytics>=8.3.162",
    "umap-learn",
    "uvicorn>=0.35.0",
    "weaviate-client>=3.26.7,<4.0.0",
    "wikipedia>=1.4.0",
]


[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = [
    { index = "pytorch-cu130", marker = "sys_platform == 'win32'" },
]
torchaudio = [
    { index = "pytorch-cu130", marker = "sys_platform == 'win32'" },
]
torchvision = [
    { index = "pytorch-cu130", marker = "sys_platform == 'win32'" },
]
